global:
  scrape_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - 'rules/*.yml'

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']